### ISSUE TITLE
Debug warning on 2024 Add Plugins page

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#92] opened 2024-02-10 18:15 UTC
I'm getting this twice on the Plugins install page on the 2024 site:

Warning: Undefined property: stdClass::$plugin in /home/wp/www/2024/wp-includes/class-wp-list-util.php on line 168

<img width="419" alt="Screenshot 2024-02-10 of warning" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/7f6907c5-21c5-4904-b96e-3877f5550383">

I'm less concerned about the actual warning and more wondering if we need to turn debug off?

**Comment by joedolson** [comment] 2024-02-10 20:10
I can't reproduce this at the moment. It's coming from the `wp_list_pluck()` utility, so it could seriously be from anywhere. If you see it again, let me know.

I'd rather leave debugging on for now, while we're still building everything out. Can disable it after we've announced.

**Comment by joedolson** [comment] 2024-03-14 19:41
Error reporting is now disabled. I'm closing this, since I have no reproduction of the initial error.

**Closed by joedolson** 2024-03-14 19:41 UTC
