### ISSUE TITLE
Footer should not use the header utility nav for social links

### ISSUE THREAD

**Issue by amberhinds** [wpa11yday/wpaccessibilityday#33] opened 2023-08-03 21:08 UTC
This references: https://github.com/wpa11yday/wpaccessibilityday/blob/76a0a71cfada87e90d29445a99d14651cf4c0f2c/src/wp-a11y-day/footer.php#L48
<img width="1291" alt="Screen Shot 2023-08-03 at 4 06 15 PM" src="https://github.com/wpa11yday/wpaccessibilityday/assets/13153456/bb1380b2-354e-4da9-9513-603ea941ace7">

I don't think that it makes sense semantically for this to be a `<nav>` element in this case. Can we just hardcode in the social icons and links in this position in an unordered list?

If it does need to be a nav menu, then I'll create an new one for this position but it should be labeled as the social nav rather than more generic utility nav.

**Comment by joedolson** [comment] 2023-08-03 21:28
I'm not clear what change you're asking for. That menu is labeled as 'Social'; do you want the label changed in some way? I do think that having it be a `nav` makes sense, but I'm not clear on the labeling problem either way.

**Comment by joedolson** [comment] 2023-08-03 21:38
But we do want those to be two separate navs, and since everything in the footer nav is a duplicate of the header nav, there's no real benefit to having it be an additional nav region.

**Closed** 2023-08-03 21:46 UTC
